CREATE TABLE real_estate_data (
    id SERIAL PRIMARY KEY,
    property_type VARCHAR(50),
    floor_area FLOAT,
    condition VARCHAR(20),
    amenities TEXT[],
    furnishing_status VARCHAR(30),
    air_conditioning BOOLEAN,
    heating BOOLEAN,
    num_rooms INT,
    num_bathrooms INT,
    price FLOAT,
    latitude FLOAT,
    longitude FLOAT,
    location VARCHAR(100),
    dist_hospital FLOAT,
    dist_school FLOAT,
    dist_bus FLOAT,
    crime_rate FLOAT,
    has_gym BOOLEAN,
    has_parking BOOLEAN,
    has_pool BOOLEAN,
    price_per_m2 FLOAT,
    district_fips_id VARCHAR(20),
    income FLOAT,
    population INT,
    avg_delay FLOAT,
    avg_severity FLOAT,
    avg_duration FLOAT,
    price_to_income_ratio FLOAT,
    transport_score FLOAT
);